import type { FoodItem } from './types';

export const FOOD_DATABASE: FoodItem[] = [
  { id: 'rice_cooked', name: 'White Rice (Cooked)', category: 'Grains', unit: 'g', defaultQty: 150, per100: { calories: 130, protein: 2.7, carbs: 28.2, fat: 0.3 } },
  { id: 'brown_rice', name: 'Brown Rice (Cooked)', category: 'Grains', unit: 'g', defaultQty: 150, per100: { calories: 123, protein: 2.7, carbs: 25.6, fat: 0.9 } },
  { id: 'basmati_rice', name: 'Basmati Rice (Cooked)', category: 'Grains', unit: 'g', defaultQty: 150, per100: { calories: 121, protein: 3.0, carbs: 25.2, fat: 0.4 } },
  { id: 'chapati', name: 'Chapati / Roti', category: 'Grains', unit: 'pieces', defaultQty: 1, per100: { calories: 297, protein: 7.9, carbs: 49.6, fat: 5.1 } },
  { id: 'whole_wheat_roti', name: 'Whole Wheat Roti', category: 'Grains', unit: 'pieces', defaultQty: 1, per100: { calories: 310, protein: 9.0, carbs: 52.0, fat: 5.5 } },
  { id: 'naan', name: 'Naan', category: 'Grains', unit: 'pieces', defaultQty: 1, per100: { calories: 310, protein: 9.1, carbs: 50.0, fat: 6.4 } },
  { id: 'paratha', name: 'Paratha (Aloo)', category: 'Grains', unit: 'pieces', defaultQty: 1, per100: { calories: 313, protein: 6.0, carbs: 40.0, fat: 13.0 } },
  { id: 'dosa_plain', name: 'Plain Dosa', category: 'Grains', unit: 'pieces', defaultQty: 1, per100: { calories: 168, protein: 3.9, carbs: 29.0, fat: 3.7 } },
  { id: 'masala_dosa', name: 'Masala Dosa', category: 'Grains', unit: 'pieces', defaultQty: 1, per100: { calories: 237, protein: 5.2, carbs: 38.0, fat: 6.0 } },
  { id: 'idli', name: 'Idli', category: 'Grains', unit: 'pieces', defaultQty: 2, per100: { calories: 146, protein: 4.0, carbs: 30.0, fat: 0.6 } },
  { id: 'uttapam', name: 'Uttapam', category: 'Grains', unit: 'pieces', defaultQty: 1, per100: { calories: 181, protein: 5.0, carbs: 30.0, fat: 4.5 } },
  { id: 'poha', name: 'Poha', category: 'Grains', unit: 'g', defaultQty: 200, per100: { calories: 130, protein: 2.6, carbs: 25.0, fat: 2.5 } },
  { id: 'upma', name: 'Upma', category: 'Grains', unit: 'g', defaultQty: 200, per100: { calories: 150, protein: 3.0, carbs: 28.0, fat: 3.0 } },
  { id: 'oats_cooked', name: 'Oats (Cooked)', category: 'Grains', unit: 'g', defaultQty: 100, per100: { calories: 71, protein: 2.5, carbs: 12.0, fat: 1.5 } },
  { id: 'oats_dry', name: 'Oats (Dry)', category: 'Grains', unit: 'g', defaultQty: 40, per100: { calories: 389, protein: 16.9, carbs: 66.3, fat: 6.9 } },
  { id: 'muesli', name: 'Muesli', category: 'Grains', unit: 'g', defaultQty: 50, per100: { calories: 366, protein: 10.0, carbs: 66.0, fat: 6.0 } },
  { id: 'daliya', name: 'Daliya (Broken Wheat)', category: 'Grains', unit: 'g', defaultQty: 200, per100: { calories: 152, protein: 3.5, carbs: 30.0, fat: 1.0 } },
  { id: 'biryani_veg', name: 'Veg Biryani', category: 'Grains', unit: 'g', defaultQty: 250, per100: { calories: 165, protein: 4.0, carbs: 25.0, fat: 5.0 } },
  { id: 'biryani_chicken', name: 'Chicken Biryani', category: 'Grains', unit: 'g', defaultQty: 250, per100: { calories: 210, protein: 12.0, carbs: 25.0, fat: 6.5 } },
  { id: 'khichdi', name: 'Khichdi', category: 'Grains', unit: 'g', defaultQty: 250, per100: { calories: 120, protein: 4.0, carbs: 22.0, fat: 2.0 } },

  { id: 'chicken_breast', name: 'Chicken Breast (Cooked)', category: 'Protein', unit: 'g', defaultQty: 150, per100: { calories: 165, protein: 31.0, carbs: 0.0, fat: 3.6 } },
  { id: 'chicken_thigh', name: 'Chicken Thigh (Cooked)', category: 'Protein', unit: 'g', defaultQty: 150, per100: { calories: 209, protein: 26.0, carbs: 0.0, fat: 11.0 } },
  { id: 'chicken_curry', name: 'Chicken Curry', category: 'Protein', unit: 'g', defaultQty: 200, per100: { calories: 175, protein: 16.0, carbs: 6.0, fat: 9.0 } },
  { id: 'tandoori_chicken', name: 'Tandoori Chicken', category: 'Protein', unit: 'g', defaultQty: 200, per100: { calories: 180, protein: 25.0, carbs: 3.0, fat: 8.0 } },
  { id: 'fish_rohu', name: 'Fish (Rohu, Cooked)', category: 'Protein', unit: 'g', defaultQty: 150, per100: { calories: 160, protein: 25.0, carbs: 0.0, fat: 6.0 } },
  { id: 'fish_pomfret', name: 'Fish (Pomfret, Cooked)', category: 'Protein', unit: 'g', defaultQty: 150, per100: { calories: 170, protein: 24.0, carbs: 0.0, fat: 7.5 } },
  { id: 'fish_salmon', name: 'Salmon (Cooked)', category: 'Protein', unit: 'g', defaultQty: 150, per100: { calories: 208, protein: 20.0, carbs: 0.0, fat: 13.0 } },
  { id: 'fish_tuna', name: 'Tuna (Cooked)', category: 'Protein', unit: 'g', defaultQty: 150, per100: { calories: 132, protein: 28.0, carbs: 0.0, fat: 1.3 } },
  { id: 'fish_prawn', name: 'Prawns (Cooked)', category: 'Protein', unit: 'g', defaultQty: 150, per100: { calories: 99, protein: 24.0, carbs: 0.2, fat: 0.3 } },
  { id: 'mutton', name: 'Mutton (Cooked)', category: 'Protein', unit: 'g', defaultQty: 150, per100: { calories: 294, protein: 25.0, carbs: 0.0, fat: 21.0 } },
  { id: 'egg_whole', name: 'Whole Egg (Boiled)', category: 'Protein', unit: 'pieces', defaultQty: 2, per100: { calories: 155, protein: 13.0, carbs: 1.1, fat: 11.0 } },
  { id: 'egg_white', name: 'Egg White', category: 'Protein', unit: 'pieces', defaultQty: 3, per100: { calories: 52, protein: 11.0, carbs: 0.7, fat: 0.2 } },
  { id: 'egg_omelette', name: 'Egg Omelette (2 egg)', category: 'Protein', unit: 'pieces', defaultQty: 1, per100: { calories: 154, protein: 11.0, carbs: 1.0, fat: 12.0 } },
  { id: 'egg_bhurji', name: 'Egg Bhurji', category: 'Protein', unit: 'g', defaultQty: 150, per100: { calories: 180, protein: 13.0, carbs: 3.0, fat: 13.0 } },
  { id: 'whey_protein', name: 'Whey Protein (1 scoop)', category: 'Protein', unit: 'pieces', defaultQty: 1, per100: { calories: 400, protein: 80.0, carbs: 8.0, fat: 6.0 } },

  { id: 'paneer_raw', name: 'Paneer (Raw)', category: 'Dairy & Protein', unit: 'g', defaultQty: 100, per100: { calories: 296, protein: 18.0, carbs: 6.0, fat: 22.0 } },
  { id: 'paneer_cooked', name: 'Paneer (Cooked)', category: 'Dairy & Protein', unit: 'g', defaultQty: 150, per100: { calories: 280, protein: 16.0, carbs: 8.0, fat: 20.0 } },
  { id: 'paneer_tikka', name: 'Paneer Tikka', category: 'Dairy & Protein', unit: 'g', defaultQty: 150, per100: { calories: 260, protein: 18.0, carbs: 7.0, fat: 16.0 } },
  { id: 'tofu', name: 'Tofu', category: 'Dairy & Protein', unit: 'g', defaultQty: 100, per100: { calories: 76, protein: 8.0, carbs: 1.9, fat: 4.8 } },
  { id: 'soya_chunks', name: 'Soya Chunks (Cooked)', category: 'Dairy & Protein', unit: 'g', defaultQty: 100, per100: { calories: 170, protein: 52.0, carbs: 33.0, fat: 0.5 } },
  { id: 'dal_tadka', name: 'Dal Tadka', category: 'Dairy & Protein', unit: 'g', defaultQty: 200, per100: { calories: 113, protein: 6.0, carbs: 16.0, fat: 3.0 } },
  { id: 'dal_makhani', name: 'Dal Makhani', category: 'Dairy & Protein', unit: 'g', defaultQty: 200, per100: { calories: 180, protein: 7.0, carbs: 18.0, fat: 9.0 } },
  { id: 'chana_masala', name: 'Chana Masala', category: 'Dairy & Protein', unit: 'g', defaultQty: 200, per100: { calories: 164, protein: 8.0, carbs: 22.0, fat: 5.0 } },
  { id: 'rajma', name: 'Rajma (Kidney Beans)', category: 'Dairy & Protein', unit: 'g', defaultQty: 200, per100: { calories: 140, protein: 8.0, carbs: 22.0, fat: 3.0 } },
  { id: 'chole', name: 'Chole (Chickpea Curry)', category: 'Dairy & Protein', unit: 'g', defaultQty: 200, per100: { calories: 150, protein: 8.0, carbs: 23.0, fat: 4.0 } },
  { id: 'moong_dal', name: 'Moong Dal (Cooked)', category: 'Dairy & Protein', unit: 'g', defaultQty: 200, per100: { calories: 105, protein: 7.0, carbs: 17.0, fat: 1.5 } },
  { id: 'sambar', name: 'Sambar', category: 'Dairy & Protein', unit: 'ml', defaultQty: 200, per100: { calories: 50, protein: 2.5, carbs: 8.0, fat: 1.0 } },

  { id: 'milk_full', name: 'Milk (Full Fat)', category: 'Dairy', unit: 'ml', defaultQty: 200, per100: { calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3 } },
  { id: 'milk_toned', name: 'Milk (Toned)', category: 'Dairy', unit: 'ml', defaultQty: 200, per100: { calories: 58, protein: 3.1, carbs: 4.7, fat: 3.0 } },
  { id: 'milk_skim', name: 'Milk (Skimmed)', category: 'Dairy', unit: 'ml', defaultQty: 200, per100: { calories: 34, protein: 3.4, carbs: 5.0, fat: 0.1 } },
  { id: 'curd', name: 'Curd / Dahi', category: 'Dairy', unit: 'g', defaultQty: 150, per100: { calories: 98, protein: 9.0, carbs: 8.0, fat: 4.3 } },
  { id: 'greek_yogurt', name: 'Greek Yogurt', category: 'Dairy', unit: 'g', defaultQty: 150, per100: { calories: 59, protein: 10.0, carbs: 3.6, fat: 0.4 } },
  { id: 'buttermilk', name: 'Buttermilk (Chaas)', category: 'Dairy', unit: 'ml', defaultQty: 250, per100: { calories: 40, protein: 2.0, carbs: 4.5, fat: 1.5 } },
  { id: 'lassi', name: 'Lassi (Sweet)', category: 'Dairy', unit: 'ml', defaultQty: 250, per100: { calories: 83, protein: 2.5, carbs: 12.0, fat: 2.5 } },
  { id: 'cheese', name: 'Cheese', category: 'Dairy', unit: 'g', defaultQty: 30, per100: { calories: 402, protein: 25.0, carbs: 1.3, fat: 33.0 } },
  { id: 'butter', name: 'Butter', category: 'Dairy', unit: 'g', defaultQty: 10, per100: { calories: 717, protein: 0.9, carbs: 0.1, fat: 81.0 } },
  { id: 'ghee', name: 'Ghee', category: 'Dairy', unit: 'g', defaultQty: 10, per100: { calories: 900, protein: 0.0, carbs: 0.0, fat: 100.0 } },
  { id: 'paneer_bhurji', name: 'Paneer Bhurji', category: 'Dairy & Protein', unit: 'g', defaultQty: 150, per100: { calories: 270, protein: 15.0, carbs: 7.0, fat: 19.0 } },

  { id: 'banana', name: 'Banana', category: 'Fruits', unit: 'pieces', defaultQty: 1, per100: { calories: 89, protein: 1.1, carbs: 22.8, fat: 0.3 } },
  { id: 'apple', name: 'Apple', category: 'Fruits', unit: 'pieces', defaultQty: 1, per100: { calories: 52, protein: 0.3, carbs: 14.0, fat: 0.2 } },
  { id: 'orange', name: 'Orange', category: 'Fruits', unit: 'pieces', defaultQty: 1, per100: { calories: 47, protein: 0.9, carbs: 12.0, fat: 0.1 } },
  { id: 'mango', name: 'Mango', category: 'Fruits', unit: 'g', defaultQty: 150, per100: { calories: 60, protein: 0.8, carbs: 15.0, fat: 0.4 } },
  { id: 'papaya', name: 'Papaya', category: 'Fruits', unit: 'g', defaultQty: 150, per100: { calories: 43, protein: 0.5, carbs: 11.0, fat: 0.3 } },
  { id: 'watermelon', name: 'Watermelon', category: 'Fruits', unit: 'g', defaultQty: 200, per100: { calories: 30, protein: 0.6, carbs: 7.6, fat: 0.2 } },
  { id: 'grapes', name: 'Grapes', category: 'Fruits', unit: 'g', defaultQty: 100, per100: { calories: 69, protein: 0.7, carbs: 18.0, fat: 0.2 } },
  { id: 'pomegranate', name: 'Pomegranate', category: 'Fruits', unit: 'g', defaultQty: 100, per100: { calories: 83, protein: 1.7, carbs: 19.0, fat: 1.2 } },
  { id: 'guava', name: 'Guava', category: 'Fruits', unit: 'pieces', defaultQty: 1, per100: { calories: 68, protein: 2.6, carbs: 14.0, fat: 1.0 } },
  { id: 'chikoo', name: 'Chikoo (Sapodilla)', category: 'Fruits', unit: 'pieces', defaultQty: 1, per100: { calories: 83, protein: 0.4, carbs: 20.0, fat: 1.1 } },

  { id: 'almonds', name: 'Almonds', category: 'Nuts', unit: 'g', defaultQty: 30, per100: { calories: 579, protein: 21.0, carbs: 21.6, fat: 49.9 } },
  { id: 'walnuts', name: 'Walnuts', category: 'Nuts', unit: 'g', defaultQty: 30, per100: { calories: 654, protein: 15.0, carbs: 13.7, fat: 65.2 } },
  { id: 'cashews', name: 'Cashews', category: 'Nuts', unit: 'g', defaultQty: 30, per100: { calories: 553, protein: 18.0, carbs: 30.2, fat: 44.0 } },
  { id: 'peanuts', name: 'Peanuts', category: 'Nuts', unit: 'g', defaultQty: 30, per100: { calories: 567, protein: 26.0, carbs: 16.1, fat: 49.2 } },
  { id: 'pista', name: 'Pistachios', category: 'Nuts', unit: 'g', defaultQty: 30, per100: { calories: 562, protein: 20.0, carbs: 28.0, fat: 45.0 } },
  { id: 'peanut_butter', name: 'Peanut Butter', category: 'Nuts', unit: 'g', defaultQty: 30, per100: { calories: 588, protein: 25.0, carbs: 20.0, fat: 50.0 } },
  { id: 'chia_seeds', name: 'Chia Seeds', category: 'Nuts', unit: 'g', defaultQty: 15, per100: { calories: 486, protein: 17.0, carbs: 42.0, fat: 31.0 } },
  { id: 'flax_seeds', name: 'Flax Seeds', category: 'Nuts', unit: 'g', defaultQty: 15, per100: { calories: 534, protein: 18.0, carbs: 29.0, fat: 42.0 } },

  { id: 'potato', name: 'Potato (Boiled)', category: 'Vegetables', unit: 'g', defaultQty: 150, per100: { calories: 87, protein: 1.9, carbs: 20.0, fat: 0.1 } },
  { id: 'sweet_potato', name: 'Sweet Potato (Boiled)', category: 'Vegetables', unit: 'g', defaultQty: 150, per100: { calories: 90, protein: 2.0, carbs: 20.7, fat: 0.1 } },
  { id: 'spinach', name: 'Palak (Spinach)', category: 'Vegetables', unit: 'g', defaultQty: 100, per100: { calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4 } },
  { id: 'broccoli', name: 'Broccoli', category: 'Vegetables', unit: 'g', defaultQty: 100, per100: { calories: 34, protein: 2.8, carbs: 7.0, fat: 0.4 } },
  { id: 'cauliflower', name: 'Cauliflower', category: 'Vegetables', unit: 'g', defaultQty: 150, per100: { calories: 25, protein: 2.0, carbs: 5.0, fat: 0.3 } },
  { id: 'cabbage', name: 'Cabbage', category: 'Vegetables', unit: 'g', defaultQty: 100, per100: { calories: 25, protein: 1.3, carbs: 5.8, fat: 0.1 } },
  { id: 'carrot', name: 'Carrot', category: 'Vegetables', unit: 'g', defaultQty: 100, per100: { calories: 41, protein: 0.9, carbs: 10.0, fat: 0.2 } },
  { id: 'tomato', name: 'Tomato', category: 'Vegetables', unit: 'g', defaultQty: 100, per100: { calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 } },
  { id: 'cucumber', name: 'Cucumber', category: 'Vegetables', unit: 'g', defaultQty: 100, per100: { calories: 15, protein: 0.7, carbs: 3.6, fat: 0.1 } },
  { id: 'onion', name: 'Onion', category: 'Vegetables', unit: 'g', defaultQty: 50, per100: { calories: 40, protein: 1.1, carbs: 9.3, fat: 0.1 } },
  { id: 'lady_finger', name: 'Bhindi (Lady Finger)', category: 'Vegetables', unit: 'g', defaultQty: 150, per100: { calories: 33, protein: 1.9, carbs: 7.5, fat: 0.2 } },
  { id: 'eggplant', name: 'Baingan (Eggplant)', category: 'Vegetables', unit: 'g', defaultQty: 150, per100: { calories: 25, protein: 1.0, carbs: 6.0, fat: 0.2 } },
  { id: 'capsicum', name: 'Capsicum (Bell Pepper)', category: 'Vegetables', unit: 'g', defaultQty: 100, per100: { calories: 31, protein: 1.0, carbs: 6.0, fat: 0.3 } },
  { id: 'mixed_veg', name: 'Mixed Vegetable Curry', category: 'Vegetables', unit: 'g', defaultQty: 200, per100: { calories: 85, protein: 2.5, carbs: 10.0, fat: 4.0 } },
  { id: 'palak_paneer', name: 'Palak Paneer', category: 'Dairy & Protein', unit: 'g', defaultQty: 200, per100: { calories: 189, protein: 11.0, carbs: 8.0, fat: 13.0 } },

  { id: 'samosa', name: 'Samosa', category: 'Snacks', unit: 'pieces', defaultQty: 1, per100: { calories: 308, protein: 5.0, carbs: 38.0, fat: 14.0 } },
  { id: 'pakora', name: 'Pakora', category: 'Snacks', unit: 'g', defaultQty: 100, per100: { calories: 250, protein: 5.0, carbs: 30.0, fat: 12.0 } },
  { id: 'vada', name: 'Medu Vada', category: 'Snacks', unit: 'pieces', defaultQty: 2, per100: { calories: 228, protein: 6.0, carbs: 32.0, fat: 8.0 } },
  { id: 'dhokla', name: 'Dhokla', category: 'Snacks', unit: 'g', defaultQty: 100, per100: { calories: 160, protein: 5.0, carbs: 25.0, fat: 4.0 } },
  { id: 'kachori', name: 'Kachori', category: 'Snacks', unit: 'pieces', defaultQty: 1, per100: { calories: 320, protein: 6.0, carbs: 35.0, fat: 16.0 } },
  { id: 'bhajiya', name: 'Bhajiya (Bhajji)', category: 'Snacks', unit: 'g', defaultQty: 100, per100: { calories: 260, protein: 6.0, carbs: 28.0, fat: 13.0 } },

  { id: 'honey', name: 'Honey', category: 'Other', unit: 'g', defaultQty: 15, per100: { calories: 304, protein: 0.3, carbs: 82.0, fat: 0.0 } },
  { id: 'jaggery', name: 'Jaggery (Gur)', category: 'Other', unit: 'g', defaultQty: 15, per100: { calories: 383, protein: 0.4, carbs: 98.0, fat: 0.1 } },
  { id: 'sugar', name: 'Sugar', category: 'Other', unit: 'g', defaultQty: 5, per100: { calories: 387, protein: 0.0, carbs: 100.0, fat: 0.0 } },
  { id: 'olive_oil', name: 'Olive Oil', category: 'Other', unit: 'ml', defaultQty: 10, per100: { calories: 884, protein: 0.0, carbs: 0.0, fat: 100.0 } },
  { id: 'coconut_water', name: 'Coconut Water', category: 'Beverages', unit: 'ml', defaultQty: 200, per100: { calories: 19, protein: 0.7, carbs: 3.7, fat: 0.2 } },
  { id: 'green_tea', name: 'Green Tea', category: 'Beverages', unit: 'ml', defaultQty: 200, per100: { calories: 1, protein: 0.0, carbs: 0.0, fat: 0.0 } },
  { id: 'black_coffee', name: 'Black Coffee', category: 'Beverages', unit: 'ml', defaultQty: 200, per100: { calories: 1, protein: 0.1, carbs: 0.0, fat: 0.0 } },
  { id: 'masala_chai', name: 'Masala Chai (with milk)', category: 'Beverages', unit: 'ml', defaultQty: 200, per100: { calories: 50, protein: 2.0, carbs: 6.0, fat: 2.0 } },
];
